### ISSUE TITLE
uncommenting #define NO_OUTPUT leads to the attached Error

### ISSUE THREAD

**Issue by eltoro0815** [oisyn/parkerwords#1]
![image](https://user-images.githubusercontent.com/18168608/189363610-37dc7a89-2e60-49ef-916e-13ee65cc8a0f.png)

**Comment by Keebler750** [comment]
Strangely, I get this same error if I COMMENT the NO_OUPUT define; exactly the opposite. Either way, I see no stdcout logging other than the stats at completion.
